### ISSUE TITLE
Looking for new owner or maintainers of tfenv

### ISSUE THREAD

**Issue by kamatama41** [Zordrak/tfenv#86]
Hi there, sorry for my late response for tfenv's issues and PRs.

As I'm now not a user of Terraform, honestly less motivated to keep on maintaining/enhancing tfenv.
So if you would like to do that, I can give its ownership to you by transferring the repository to your account or organization.

If you are interested in it, please let me know by commenting to this issue or sending email (you can see my address in [the profile page](https://github.com/kamatama41)) to me.

Thank you 🙇 

P.S.
I also welcome you to just become a maintainer (collaborator)!

**Comment by kamatama41** [comment]
@umisora stood as a maintainer. Thank you very much!

**Comment by umisora** [comment]
@kamatama41  Thank you message. I try to support you ^^

**Comment by Zordrak** [comment]
I am sorry that while I am happy to remain a maintainer, I do not believe I have enough time available to dedicate to being the project owner.

**Comment by kmaris** [comment]
Hi @kamatama41 I too would be glad to help maintain the scripts :)

**Comment by pvladimi** [comment]
I will be happy to own the repo if you need anyone to manage it. I am active user of Terraform.

**Comment by Zordrak** [comment]
@kamatama41 I have changed my mind. Continued dependence of terraformscaffold on tfenv and wide use of both across so many projects makes it simply inescapable that I should find time to manage tfenv. I am happy to take ownership.

**Comment by genevera** [comment]
I'm happy to contribute! @kamatama41

**Comment by kamatama41** [comment]
Hi, @espoelstra @genevera 
Thank you for commenting and sorry for late reply 🙇 
If you don't change your mind, I'd be happy to add you to collaborator.

**Comment by kamatama41** [comment]
Hi, @pvladimi and @Zordrak 
Thank you for commenting about its ownership, but I have to decide either of you as new owner.  I personally think @Zordrak should be the new owner because they are already a collaborator thus familiar with tfenv, and have a obvious reason to maintain tfenv. However, if @pvladimi has strong interest or reason to own it, I can consider it :)  What do you think?

**Comment by genevera** [comment]
I'd love to be added as a collaborator :)

**Comment by grimoh117** [comment]
@kamatama41 Thank you. I'll do my best.

**Comment by kamatama41** [comment]
@genevera Thanks, I have invited you. Please check issues and PRs as much as possible 🙇

**Comment by kamatama41** [comment]
I decided @Zordrak to be the new owner. The main reason is commented [here](https://github.com/kamatama41/tfenv/issues/86#issuecomment-400116212) and @Zordrak approved this by a communication outside of this issue. So I will transfer this repository to https://github.com/Zordrak soon (probably within 2 days).

@pvladimi I'm sorry for this decision before your comment, but really appreciate that you raise your hand to volunteer :)

**Comment by kamatama41** [comment]
@grimoh117 Thank you for raising your hand as a maintainer!

**Comment by kamatama41** [comment]
Transfer tfenv to https://github.com/Zordrak/tfenv has been done. Thank you for all your cooperation!
